language: perl
perl:
  - "5.26"
env:
  - "HARNESS_OPTIONS=j6"
install:
  - "cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov"
  - "cpanm -n Test::Pod Test::Pod::Coverage YAML"
  - "cpanm -n --installdeps ."
notifications:
  email: true
matrix:
  include:
    - perl: 5.26
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
after_success:
  - cover -report codecov
