name = "Mojolicious-Plugin-Prometheus"
# badges = ["travis"]
module_maker="ModuleBuildTiny"
tag_format="v%v"
authority="cpan:TYLDUM"
license="artistic_2"
badges = ['travis','metacpan']

[FileGatherer]
include_dotfiles = false

