name = "Mojolicious-Plugin-Prometheus"
# badges = ["travis"]
module_maker="ModuleBuildTiny"
tag_format="v%v"
authority="cpan:TYLDUM"
license="artistic_2"

[FileGatherer]
include_dotfiles = false

badges = ['travis','metacpan']

[release]
do_not_upload_to_cpan=false

